runtime: python310
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  BUCKET_NAME: "your-bucket-name"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5


