runtime: python39
env: flex

# Gunicorn configuration optimized for low usage
entrypoint: gunicorn -w 2 -b :$PORT app:server  # 2 workers should be sufficient for handling 2-3 users

# Basic scaling settings
basic_scaling:
  max_instances: 2  # Limits the maximum number of instances to 2
  idle_timeout: 300s  # Instances are shut down after 5 minutes of inactivity

resources:
  cpu: 1
  memory_gb: 0.5  # Adjust if your application is memory intensive
  disk_size_gb: 10  # Adjust based on the size of your application and any data stored locally

env_variables:
  BUCKET_NAME: "dinex_bucket"

