runtime: python39
env: standard

entrypoint: gunicorn -w 2 -b :$PORT app:server  # Reduced number of workers for lower traffic

automatic_scaling:
  min_idle_instances: 1  # Minimum number of idle instances
  max_idle_instances: 2  # Maximum number of idle instances
  min_instances: 1  # Minimum number of running instances
  max_instances: 2  # Maximum number of running instances
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75

# Resources section is not used in the standard environment
# App Engine Standard environment automatically scales instances and manages resources.

env_variables:
  BUCKET_NAME: "dinex_bucket"
