runtime: python39
env: flex

entrypoint: gunicorn -w 2 -b :$PORT app:server  # Reduced number of workers for lower traffic

automatic_scaling:
  min_num_instances: 1  # Keep at least one instance running
  max_num_instances: 2  # Limit to two instances to control costs
  cool_down_period_sec: 120  # Longer cooldown period to prevent rapid scaling
  cpu_utilization:
    target_utilization: 0.75  # Allow higher CPU utilization before scaling

resources:
  cpu: 1
  memory_gb: 0.5  # Sufficient for small-scale data processing
  disk_size_gb: 10  # Default disk size, adjust if more storage is needed

env_variables:
  BUCKET_NAME: "dinex_bucket"


