runtime: python39
env: flex

entrypoint: gunicorn -b :$PORT app:server

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.75

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  BUCKET_NAME: "dinex_bucket"
