runtime: python39  # specify your Python runtime

entrypoint: gunicorn -b :$PORT index:server

env_variables:
  BUCKET_NAME: 'dinex_bucket'
  # Set other environment variables as needed.

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_idle_instances: auto
  max_idle_instances: auto  # Adjust these settings based on your needs.
  min_instances: 1
  max_instances: 5
