runtime: python39
env: flex  # Changed from standard to flexible

entrypoint: gunicorn -b :$PORT app:server  # Reduced number of workers for lower traffic

automatic_scaling:
  min_num_instances: 1  # Minimum number of instances
  max_num_instances: 2  # Maximum number of instances
  cpu_utilization:
    target_utilization: 0.75

resources:  # Define the computing resources per instance
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10  # Adjust disk size as necessary

env_variables:
  BUCKET_NAME: "dinex_bucket"

